mode:
  default: 1
  help: "0 - CONST, ручное управление: выставляем команду соответствием с gas_throttle,\
    \ air_hrottle\n\t1 - ПИД-регулятор, команда автоматически меняется поддерживая\
    \ заданный rpm (требует настройки коэффициентов)\n\t2 - RPMCommand, контроль занчений\
    \ оборотов осуществяется на самой плате ice_node,\n\t3 - Проверка стартера, двигатель\
    \ запускается на 8 секунд\n\t4 - Запуск двигателя с закрытой воздушной заслонкой\
    \ на 60 секунд"
  value: 0
  min: 0
  max: 4
  unit: ''
  type: int
  usage: base

rpm:
  default: 4500
  help: Целевые обороты ДВС
  value: 4000
  min: 0
  max: 12000
  unit: 1/min
  type: int
  usage: base

time:
  default: 10
  help: Время в секундах, через которое скрипт автоматически закончит свое выполнение
  value: 100
  min: 0
  max: 3600
  unit: sec
  type: int
  usage: base

gas_throttle:
  default: 0
  help: Положение дроссельной заслонки
  value: 40
  min: 0
  max: 100
  unit: '%'
  type: int
  usage: base

air_throttle:
  default: 0
  help: Положение воздушной заслонки
  value: 0
  min: 0
  max: 100
  unit: '%'
  type: int
  usage: base

min_gas_throttle:
  default: 0
  help: Минимальное значение дроссельной заслонки, которое будет отправляться, используется
    для mode 1
  value: 0
  min: 0
  max: 100
  unit: '%'
  type: int
  usage: other

max_gas_throttle:
  default: 0
  help: Максимальное значение дроссельной заслонки, которое будет отправляться, используется
    для mode 1
  value: 75
  min: 0
  max: 100
  unit: '%'
  type: int
  usage: other

report_period:
  help: Период отправки dronecan, status, state сообщений на сервер
  value: 10
  min: 0
  max: 60
  unit: sec
  type: int
  usage: other

control_pid_p:
  help: Коэффициент p для ПИД регулятора
  value: 0.0
  min: 0
  max: 999
  unit: ''
  type: float
  usage: other

control_pid_i:
  help: Коэффициент i для ПИД регулятора
  value: 0.0
  min: 0
  max: 999
  unit: ''
  type: float
  usage: other

control_pid_d:
  help: Коэффициент d для ПИД регулятора
  value: 0.0
  min: 0
  max: 999
  unit: ''
  type: float
  usage: other

max_temperature:
  help: Граничная температура двигателя, при достижении обкатка обрывается
  value: 190
  min: 0
  max: 210
  unit: sec
  type: int
  usage: flag

min_fuel_volume:
  help: Граничный уровень топлива, при достижении обкатка обрывается
  value: 0
  min: 0
  max: 100
  unit: '%'
  type: int
  usage: flag

min_vin_voltage:
  help: Граничнное входное напряжение, при достижении обкатка обрывается
  value: 0.0
  min: 0
  max: 60.0
  unit: Volts
  type: float
  usage: flag

start_attemts:
  help: Количество попыток запуска двигателя на всю обкатку
  value: 3
  min: 1
  max: 5
  unit: ''
  type: int
  usage: flag

max_vibration:
  help: Максимальный уровень вибраций
  value: 1000
  min: 0
  max: 2000
  unit: ''
  type: int
  usage: flag
