command:
  default: 0
  help: Команда на N оборотов (RPMCommand) без ПИД-регулятора
  value: 0
max_gas_throttle:
  default: 100
  help: Максимальное допустимый уровень газовой заслонки в процентах. Значение 100
    означает, что нет ограничений.
  value: 100
max_temperature:
  default: 190
  help: Максимальная допустимая температура ДВС, после которой скрипт завершит выполнение
  value: 1282.6
max_vibration:
  default: 1000
  help: Максимальный допустимый уровень вибрации
  value: 1000
min_fuel_volume:
  default: 0
  help: Минимальный уровень топлива (процент или cm3), после которого прекращаем обкатку/выдаем
    предупреждение.
  value: 0
mode:
  default: 0
  help: 'Есть 3 варианта работы: 0 - просто сразу же выставляем команду, 1 - ПИД-регулятор
    на стороне скрипта, 2 - ПИД-регулятор на стороне платы'
  value: 0
report_period:
  default: 10
  help: 'Период публикации статус сообщения в секундах '
  value: 10
rpm:
  default: 4500
  help: Целевые обороты ДВС
  value: '1000'
time:
  default: 600
  help: Время в секундах, через которое скрипт автоматически закончит свое выполнение
  value: 600
