version: 1
disable_existing_loggers: true

handlers:
  fileHandler: 
    class: logging.handlers.TimedRotatingFileHandler
    formatter: brief
    filename: logs/nodes_interface.log

  consoleHandler: 
    class: logging.StreamHandler
    formatter: precise

  rawMessageHandler:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: rawMessage
    filename: logs/raw_messages.log

loggers:
  root:
    level: DEBUG
    handlers: [fileHandler, consoleHandler]
  ice_commander:
    level: DEBUG
    handlers: [rawMessageHandler]
    propagate: 0

# Root logger should be specified if common settings are needed
root:
  level: DEBUG
  handlers: [fileHandler, consoleHandler]

formatters:
  brief:
    format: "%(asctime)s | %(levelname)-8s | %(filename)s-%(lineno)04d | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  precise:
    format: "%(asctime)s | %(levelname)-8s | %(filename)s-%(funcName)s-%(lineno)04d | %(message)s"
    datefmt: "%H:%M:%S"
  rawMessage:
    format: "%(asctime)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
