version: 1
disable_existing_loggers: true

handlers:
  fileHandler:
    class: logging.FileHandler  # Change to FileHandler programmatically
    formatter: brief
    filename: placeholder.log  # Placeholder to be replaced programmatically

  consoleHandler:
    class: logging.StreamHandler
    formatter: precise

loggers:
  root:
    level: DEBUG
    handlers: [fileHandler, consoleHandler]

# Root logger should be specified if common settings are needed
root:
  level: DEBUG
  handlers: [fileHandler, consoleHandler]

formatters:
  brief:
    format: "%(asctime)s | %(levelname)-6s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  precise:
    format: "%(asctime)s | %(levelname)-8s | %(filename)-20s | %(message)s"
    datefmt: "%H:%M:%S"
  rawMessage:
    format: "%(asctime)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
