version: 1
# disable_existing_loggers: true
# propagate: false

handlers:
  fileHandler:
    class: logging.TimedRotatingFileHandler  # Change to FileHandler programmatically
    filename: placeholder.log  # Placeholder to be replaced programmatically
    when: h
    interval: 1
    backupCount: 10
    level: DEBUG

  consoleHandler:
    class: logging.StreamHandler
    formatter: precise
    level: INFO

# Root logger should be specified if common settings are needed
root:
  level: DEBUG
  handlers: [fileHandler, consoleHandler]

formatters:
  brief:
    format: "%(asctime)s - %(levelname)-8s - %(filename)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  precise:
    format: "%(asctime)s - %(levelname)-8s - %(filename)s - %(message)s"
    datefmt: "%H:%M:%S"
