name: check_github
on: [push, pull_request]

jobs:
  multi_os_check:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-22.04

          - runs-on: windows-2022

          - runs-on: ubuntu-latest
            container: archlinux:latest

    runs-on: ${{ matrix.runs-on }}
    container: ${{matrix.container}}

    steps:
      - name: Install Git and dependencies
        run: |
          if [[ -f /etc/os-release ]]; then
            . /etc/os-release
            echo "OS: $NAME"
            if [[ "$NAME" == "Arch Linux" ]]; then
              pacman -Sy --noconfirm git
            fi
          fi
        shell: bash

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Detect OS
        run: |
          if [[ -f /etc/os-release ]]; then
            . /etc/os-release
            echo "OS: $NAME"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "OS: Windows"
          fi
        shell: bash
