name: check_github
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
jobs:
  build_and_deploy:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-22.04
            target: all

          - runs-on: windows-2022
            target: dronecan_v2

          - runs-on: ubuntu-22.04
            container: manjaro/base:latest
            target: "all"

    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies (Ubuntu & Manjaro & Windows)
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            if [[ -f /etc/os-release ]]; then
              . /etc/os-release
              echo "Running on $NAME"
            else
              echo "Linux OS detected but /etc/os-release not found"
            fi
          else
            [System.Environment]::OSVersion.Version
          fi
        shell: bash
