name: pylint
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
jobs:

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install virtualenv
        python -m venv venv
        source ./venv/bin/activate
        pip install pylint
        pip install -e .
    - name: Analyzing the code with pylint
      run: |
        source ./venv/bin/activate
        pylint $(git ls-files -- '*.py')
