name: pytests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
jobs:

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Install can-utils
      run:  |
        sudo apt-get update & sudo apt-get install -y can-utils
        sudo apt-get install -y linux-modules-extra-6.11.0-1015-azure
        sudo apt-get install can-utils net-tools iproute2
        sudo depmod

    - name: Start vcan
      run: |
        sudo modprobe vcan
        sudo ip link add dev slcan0 type vcan
        sudo ip link set up slcan0

    - name: Install mqtt
      run: ./scripts/install_mqtt.sh

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install virtualenv
        python -m venv venv
        source ./venv/bin/activate
        pip install -e .
        pip install -r requirements.txt

    - name: Run pytests
      run: |
        source ./venv/bin/activate
        pytest
