name: pytests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'
jobs:

  pytest:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Install can-utils
      run: |
        sudo apt install -y net-tools can-utils iproute2
    - name: Install mqtt
      run: sudo ./scripts/install_mqtt.sh
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install virtualenv
        python -m venv venv
        source ./venv/bin/activate
        pip install pylint
        pip install -e .
        pip install -r requirements.txt
    - name: Start vcan
      run:
        modprobe vcan
        ip link add dev slcan0 type vcan
        ip link set up slcan0

    - name: Analyzing the code with pylint
      run: |
        source ./venv/bin/activate
        pytest
