version: 1
disable_existing_loggers: true

handlers:
  fileHandler: 
    class: logging.handlers.TimedRotatingFileHandler
    formatter: brief
    filename: logs/nodes_interface.log

  consoleHandler: 
    class: logging.StreamHandler
    formatter: precise

loggers:
  root:
    level: DEBUG
    handlers: [fileHandler, consoleHandler]
  DronecanMessages:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: 0
  nodes_types:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: 0
  nodes_configurator:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: 0
  communication_with_nodes:
    level: DEBUG
    handlers: [fileHandler]
    propagate: 1

# Root logger should be specified if common settings are needed
root:
  level: DEBUG
  handlers: [fileHandler, consoleHandler]
    # handlers: [h1, h2]

formatters:
  brief:
    format: "%(asctime)s | %(levelname)-8s | %(filename)s-%(lineno)04d | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  precise:
    format: "%(asctime)s | %(levelname)-8s | %(filename)s-%(funcName)s-%(lineno)04d | %(message)s"
    datefmt: "%H:%M:%S"
